### ISSUE TITLE
is Windows

### ISSUE THREAD

**Issue by IDrakon** [artoale/brackets-terminal#30]
sprint 3 build 1.3.0-16022 (release cd0a6aae5) 

Плагин не работает под windows

**Comment by daniellucas** [comment]
* The plugin does not work under windows

I guess so, frustrating, the documentation needed to say it.

**Comment by artoale** [comment]
From the Readme:

>## Requirement

>*nix environment (may work with Cygwin or similar, but not tested)
>node.js and npm installed

Which means that you can try to make it work with windows (it's possible, but requires loads of extra cares). This plugin doesn't officially support that, sorry :(

**Comment by IDrakon** [comment]
Very sad :-1:
