### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ficristo** [artoale/brackets-terminal#41]
I'm mildly interested in contributing at this project, at least to remove some deprecation warnings.
Are you open to accept PR?

**Comment by artoale** [comment]
I'd rather have someone maintain directly, but I don't mind accepting pull requests :)

**Comment by ficristo** [comment]
Actually I'm trying to move to xterm.js but probably it requires a rewrite of the plugin (I've hacked something together but I'm not there yet, it will take some time)
Also I would like to convert to ESLint.
If you are open to these changes could you add me as a committer?

**Comment by ficristo** [comment]
Never mind to add me as a committer. Actually I prefer to do something of my own.
The PR I opened is still valid though.
