### ISSUE TITLE
Space bar not inserting spaces into brackets terminal

### ISSUE THREAD

**Issue by Rimann91** [artoale/brackets-terminal#45]
I am unable to enter spaces in the terminal. This makes brackets terminal completely unusable to me. This may be related to issue #29. I am using Ubuntu 16.04

**Comment by jlam55555** [comment]
I have the same issue. I am also using (x)Ubuntu 16.04.

Interestingly, spaces work at first when you open the Brackets Terminal, but stop working after you click anywhere. So my quick workaround right now is clicking outside of the terminal whenever this happens and then doing a quick Shift-Ctrl-P twice. Hope this helps you for now @Rimann91 
 
Update: I just realized that this workaround only works when you have a file open. If you have no files open, I can't seem to get spaces to work at all. Strange.
